export * from './DetailMovie/DetailMovie'
export * from './MoviesList/MoviesList'
export * from './MoviesListCard/MoviesListCard'
export * from './Header/Header'
export * from './Genre/Genre'
export * from './Genres/Genres'
export * from './Search/Search'
export * from './SearchResults/SearchResults'